### ISSUE TITLE
Can't change font

### ISSUE THREAD

**Issue by coyotwill** [yousseb/meld#38]
Meld build 3.16.0 r1 (osx-9) + macOS Sierra 10.12.4

I just installed Meld by moving the .App in my /Applications folder.

Now when I run it and try to change the editor font, it seems to always fail and fallback to a non-monospaced font. The result is hard to read. (see attached capture)
![meld](https://cloud.githubusercontent.com/assets/13336678/25455392/a1fe336c-2a9d-11e7-8c94-abdea4d561a5.jpg)

If I start Meld from a terminal (cd cd /Applications/Meld.app/Contents/MacOS/; Meld), I can see the following message in the console, when the editor is opened: `(meld:7990): Pango-WARNING **: couldn't load font "Courier New Bold Condensed Not-Rotated 14", modified variant/weight/stretch as fallback, expect ugly output.`
This not quite right since I chose Courier New Regular from the Preferences Window.

This fails for any font.

Using the default font is working fine.

**Comment by erictabellion** [comment]
I have exactly the same issue. For me this is a deal breaker, the font is just too small on a retina display. It's too bad, the description on the main web page mentioned support for "retina display", so I was hopeful. I'll have to chase for another diff & merge tool that is more friendly on the eyes unless we can get some quick resolution.

**Comment by yousseb** [comment]
3.19.0 should fix this issue.

**Comment by coyotwill** [comment]
Hi @yousseb, thanks for the heads up, but unfortunately 3.19 did not fox this for me (on High Sierra, 10.13.2).
When "Use system fixed font" is checked, the UI uses a monospaced font so tiny that it's almost impossible to read. 
And when I uncheck the box, the UI ignores my choice and still displays the same non-monospaced font.

**Comment by asimonov** [comment]
yes, I think it is fixed in 3.19 on high sierra

**Comment by kbd** [comment]
> yes, I think it is fixed in 3.19 on high sierra

Not fixed for me. Checking "Use the system fixed width font" does have an effect, but choosing any other font by selecting the "Editor font" does not work correctly.

**Comment by chipolson** [comment]
I have the exact same problem. Meld is unusable as a result.

**Comment by chipolson** [comment]
Interestingly, the small font problem only occurs on the built-in Retina display of my Macbook. On the external non-Retina display, it's fine. Changing the font still doesn't work, however.

**Comment by benstse** [comment]
I too see this issue on High Sierra 10.13.6 MacPro Retina. Changing the font does not stick. I wanted to changed to a fixed with font and it never seems to work. Choosing the "system font" option is too small on the laptop screen. Using "system font" is fine when my Mac is connected to a large display.

I'm running Meld 3.19.0.

**Comment by munepi** [comment]
@benstse 
> Changing the font does not stick.

Yes!

But, Meld macOS-ported by @yousseb use plist preference `~/Library/Preferences/org.gnome.meld.plist`. 
So, you can set Meld's custom font with `defaults` CLI. 
Indeed, you can get your current settings of Meld preferences.

``` bash
$ defaults write org.gnome.meld
```

Then, you can set to turn-off use system font: 

``` bash
$ defauls write org.gnome.meld "/org/gnome/meld/use-system-font" = 0
```

and set to chose custom font: 

``` bash
$ defaults write org.gnome.meld "/org/gnome/meld/custom-font" = "Ricty, 20"
```

If you would like to change other keys, please check   `/Applications/Meld.app//Contents/Resources/share/meld/org.gnome.meld.gschema.xml`.

**Comment by austinbutler** [comment]
Seems the syntax has change somewhat since the post above.

What works now:
`defaults write org.gnome.meld "/org/gnome/meld/use-system-font" 0`
`defaults write org.gnome.meld "/org/gnome/meld/custom-font" "Source Code Pro, 12"`

**Comment by bbottema** [comment]
This is still an issue with 3.21.0.osx3 on Big Sur

**Comment by hbarahona** [comment]
Problems still present in Monterey 12.0.1 using version 3.21.0.osx3

**Comment by DarkTrick** [comment]
> Problems still present in Monterey 12.0.1 using version 3.21.0.osx3

here too

**Comment by et304383** [comment]
Same issue on MacOS Ventura 13.1

**Comment by jconnolly** [comment]
I fixed it, got it to use JetBrains Mono 18.... then it crashed on me like half way into modifying a document. Time to shelve meld for me.

**Comment by Mugane** [comment]
Still an issue almost a decade later. Can't even make any changes in the settings menu. Nothing responds. Sort of useless.

**Comment by munepi** [comment]
You have recently been available for another macOS-ported Meld [dehesselle-meld — Homebrew Formulae](https://formulae.brew.sh/cask/meld).

Incidentally, the latest build [OSX - 3.21.0 (r4) Sonoma](https://github.com/yousseb/meld/releases/tag/osx-20) even now works via Rosetta 2 on recent macOSs.

**Comment by asimonov** [comment]
> You have recently been available for another macOS-ported Meld [dehesselle-meld — Homebrew Formulae](https://formulae.brew.sh/cask/dehesselle-meld).
> 
> Incidentally, the latest build [OSX - 3.21.0 (r4) Sonoma](https://github.com/yousseb/meld/releases/tag/osx-20) even now works via Rosetta 2 on recent macOSs.

it would be great to see ARM/apple silicon native binaries.

the x86 ones are not working great with new macs

but does not look like this project is maintained for last few years :(

**Comment by yougotwill** [comment]
Check out https://gitlab.com/dehesselle/meld_macos

We now have native arm64 builds. The homebrew formula also got updated `brew install meld`.

I had issues with the UI font but if you create a `gtk.css` in `~/Library/Application Support/org.gnome.Meld/gtk-3.0` everything works nicely.

```css
* {
    font-family: "Helvetica Neue", Arial, sans-serif;
    font-size: 14px;
}
```

<img width="951" alt="Image" src="https://github.com/user-attachments/assets/5852c0ec-8cfb-464f-815d-91892711fc3f" />

**Comment by dehesselle** [comment]
There is an upstream issue for this https://gitlab.gnome.org/GNOME/meld/-/issues/908

But I cannot fix things without feedback.

**Comment by yougotwill** [comment]
@dehesselle I have replied
