### ISSUE TITLE
Latest version crashes when trying to copy folder

### ISSUE THREAD

**Issue by transamericamoon** [yousseb/meld#57]
Latest version crashes when i try to copy a folder from one side to another via right click menu.  Crash report attached.

[crashreport.txt](https://github.com/yousseb/meld/files/1652440/crashreport.txt)

**Comment by dvska** [comment]
yeah,

/Applications/Meld.app/Contents/MacOS
dyld: lazy symbol binding failed: Symbol not found: _utimensat
  Referenced from: /Applications/Meld.app/Contents/Frameworks/libpython3.6.dylib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _utimensat
  Referenced from: /Applications/Meld.app/Contents/Frameworks/libpython3.6.dylib
  Expected in: /usr/lib/libSystem.B.dylib

**Comment by fanjindong** [comment]
+1 !!

**Comment by yongzhi2** [comment]
same issue copying a file, file is actually copied the the app crashes immediately

**Comment by hobson** [comment]
+1 same here

**Comment by NikolausDemmel** [comment]
I'm also affected on Mac OS Sierra 10.12.6.

**Comment by yousseb** [comment]
Fixed in latest release.

**Comment by NikolausDemmel** [comment]
@yousseb, thanks for looking into this. I just tried the latest "3.19.2 (r2)", but it still crashes when copying a folder:

```
 (1006)ted in: /usr/lib/libSystem.B.dylib/Contents/Frameworks/libpython3.6.dylibSymbol not found: _utimensat
```

I'm on Sierra 10.12.6.

**Comment by lemuelmc** [comment]
Hi @yousseb crashes not only happening with copying folders. Crashes when you copy anything at all. Copying/Moving regardless if it is a file or a directory will result in crash.

See report below:

Process:               Meld [16685]
Path:                  /Users/USER/*/Meld.app/Contents/MacOS/Meld
Identifier:            org.gnome.meld
Version:               3.19.2.osx6 (3.19.2.osx6)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Meld [16685]
User ID:               2044085254

Date/Time:             2019-01-10 14:44:54.851 +0800
OS Version:            Mac OS X 10.12.6 (16G1710)

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x4] Symbol missing

Dyld Error Message:
  Symbol not found: _utimensat
  Referenced from: /Users/USER/*/Meld.app/Contents/Frameworks/libpython3.6.dylib
  Expected in: /usr/lib/libSystem.B.dylib
